# Generated by Django 3.1.5 on 2021-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'passengers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
            ],
            options={
                'db_table': 'passenger_seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('seats_taken', models.IntegerField()),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choferes',
        ),
        migrations.DeleteModel(
            name='Pasajeros',
        ),
        migrations.DeleteModel(
            name='PasajerosAsientos',
        ),
        migrations.DeleteModel(
            name='Trayecto',
        ),
        migrations.DeleteModel(
            name='Viajes',
        ),
    ]
